### ISSUE TITLE
[AI and Map] Personnalize map: Use tags as meta-categories

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#105]
User story: The user adds resources and wants to group them on the map by not only concepts but also a specific meta category. They create a tag corresponding to the category, annotate resources with this tag while adding. Then, they go to the map and chose to use tag a1, ...an as meta category (example: methodology).
They click on "regenerate map" and the map appears where resources are first grouped by meta category, then within each meta category by concepts. The regions for a specific meta category would be ideally in the background colored with a specific color and their name would be indicated if we zoom out of the concepts. The user then should keep this personalization while adding new resources.

- [ ] Dropdown menu called Meta categories and choice between None(default), and all tags used.

- [ ] Button to regenerate map

- [ ] An algorithm that takes into account this meta grouping first

- [ ] The annotation of the map with these meta-categories (and eventually the background color)

- [ ] Capacity to keep such a personalized visualization when the user logs out and logs in to account, or when user shares map.
