### ISSUE TITLE
NUS WeLearn testing

### ISSUE THREAD

**Issue by iryna1** [CyberCRI/learn-ext#121]
- [x] create NUS group

- [x] provide tutorial video

- [x] provide feedback form

- [x] interview teachers (Fun Man and Lucas)

- [x] analyze feedback

**Comment by iryna1** [comment]
Last news:
Le 9 mars 2020 à 12:34, Lucas Tay Hao Yang <lucastay@u.nus.edu> a écrit :

Dear Iryna,
 
Thank you for the email, WeLearn is doing great!
We will implement it to our students in 2 weeks time.
 
The Coronavirus is sure a very hot topic, especially in Singapore.
I will see check out the resources and get back to you soon!

**Comment by iryna1** [comment]
fb and interviews: will be done in 2 weeks.
