### ISSUE TITLE
Academic disciplines on map

### ISSUE THREAD

**Issue by jmsevin** [CyberCRI/learn-ext#184]
Use a mix of portals and academic disciplines as proxies on the map, to help WeLearn navigate.
- [x] Get the list of academic disciplines from Wikipedia
- [x] Generate JSON file of academic disciplines location
- [ ] Preview academic disciplines on map
- [ ] Select portals to keep
- [ ] Remove duplicates (portal and academic discipline)
